const data = [
    {
        id: 11,
        grade: 21,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 12,
        grade: 27,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 13,
        grade: 98,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 14,
        grade: 34,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 15,
        grade: 91,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 16,
        grade: 86,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 17,
        grade: 31,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 18,
        grade: 67,
        company: "IconScout",
        location: '261 Erdman Ford',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/21/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 19,
        grade: 21,
        company: "Ceat",
        location: '12 str, 122 rd',
        website: "www.anonymous.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "09/03/2023",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.crunchbase.co",
        source: "Howstats"
    },
    {
        id: 20,
        grade: 98,
        company: "Villa",
        location: '261 str, NY',
        website: "www.loremupispum.com",
        linkedin: "www.linkedin.com/concen",
        founder: "www.linkedin.com/john",
        date: "12/01/2022",
        owner: "",
        type: 0,
        email: "howard@icon.com",
        profile: "www.ville.co",
        source: "Howstats"
    },
];


export default data;